# Generated by Django 4.2.3 on 2023-07-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0006_patient_psychologue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='statut',
            field=models.CharField(choices=[('psychologue', 'Psychologue'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
